-- Initial schema for handball app.

DROP TYPE IF EXISTS public.match_result;
CREATE TYPE public.match_result AS ENUM ('WIN', 'LOST', 'FINISHED');

CREATE TABLE IF NOT EXISTS public.team (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  createdat timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.player (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teamid integer NOT NULL REFERENCES public.team(id) ON DELETE CASCADE,
  name text NOT NULL,
  number integer NOT NULL,
  position text NOT NULL,
  createdat timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.match (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teamid integer NOT NULL REFERENCES public.team(id) ON DELETE CASCADE,
  opponent text NOT NULL,
  score integer NOT NULL DEFAULT 0,
  "opponentScore" integer NOT NULL DEFAULT 0,
  result public.match_result,
  "timeoutsLeftHome" integer NOT NULL DEFAULT 3,
  "timeoutsLeftAway" integer NOT NULL DEFAULT 3,
  createdat timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.player_stats (
  playerid integer NOT NULL REFERENCES public.player(id) ON DELETE CASCADE,
  matchid integer NOT NULL REFERENCES public.match(id) ON DELETE CASCADE,
  goal integer NOT NULL DEFAULT 0,
  goal_empty integer NOT NULL DEFAULT 0,
  miss integer NOT NULL DEFAULT 0,
  gksave integer NOT NULL DEFAULT 0,
  gkmiss integer NOT NULL DEFAULT 0,
  gkmiss_empty integer NOT NULL DEFAULT 0,
  assistprimary integer NOT NULL DEFAULT 0,
  assistsecondary integer NOT NULL DEFAULT 0,
  lostball integer NOT NULL DEFAULT 0,
  "provokePenalty" integer NOT NULL DEFAULT 0,
  "provokeTwoMin" integer NOT NULL DEFAULT 0,
  "provokeCard" integer NOT NULL DEFAULT 0,
  "1on1win" integer NOT NULL DEFAULT 0,
  steal integer NOT NULL DEFAULT 0,
  block integer NOT NULL DEFAULT 0,
  defense integer NOT NULL DEFAULT 0,
  defensex2 integer NOT NULL DEFAULT 0,
  "1on1lost" integer NOT NULL DEFAULT 0,
  penaltymade integer NOT NULL DEFAULT 0,
  norebound integer NOT NULL DEFAULT 0,
  twominutes integer NOT NULL DEFAULT 0,
  yellowcard integer NOT NULL DEFAULT 0,
  redcard integer NOT NULL DEFAULT 0,
  bluecard integer NOT NULL DEFAULT 0,
  value numeric NOT NULL DEFAULT 0,
  PRIMARY KEY (matchid, playerid)
);

CREATE TABLE IF NOT EXISTS public.shots (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  matchid integer NOT NULL REFERENCES public.match(id) ON DELETE CASCADE,
  playerid integer NOT NULL REFERENCES public.player(id) ON DELETE CASCADE,
  "assistPrimary" integer REFERENCES public.player(id) ON DELETE SET NULL,
  "assistSecondary" integer REFERENCES public.player(id) ON DELETE SET NULL,
  "mistakePlayer" integer REFERENCES public.player(id) ON DELETE SET NULL,
  result text NOT NULL,
  time text NOT NULL,
  "from" text NOT NULL,
  "to" integer NOT NULL,
  fastbreak boolean NOT NULL DEFAULT false,
  breakthrough boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.match_event (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  matchid integer NOT NULL REFERENCES public.match(id) ON DELETE CASCADE,
  event text NOT NULL,
  time text NOT NULL,
  playerid integer REFERENCES public.player(id) ON DELETE SET NULL,
  metadata text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.increment_match_score(
  column_name text,
  matchid integer
) RETURNS void AS $$
BEGIN
  EXECUTE format(
    'UPDATE public.match
     SET %I = %I + 1
     WHERE id = $1',
    column_name, column_name
  )
  USING matchid;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.increment_stat(
  column_name text,
  matchid integer,
  playerid integer
) RETURNS void AS $$
BEGIN
  EXECUTE format(
    'UPDATE public.player_stats
     SET %I = %I + 1
     WHERE matchid = $1 AND playerid = $2',
    column_name, column_name
  )
  USING matchid, playerid;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.compute_player_value(
  p_player_id integer,
  p_match_id integer
) RETURNS numeric AS $$
  SELECT
    FLOOR(
      CASE
        WHEN (ps.gksave + ps.gkmiss) > 0
        THEN (ps.gksave::numeric / (ps.gksave + ps.gkmiss)) * 10
        ELSE 0
      END
    )
    + (ps.goal - ps.miss)
    + ((ps.assistprimary + ps.assistsecondary + ps."provokePenalty" + ps."provokeTwoMin" + ps."provokeCard" + ps."1on1win") - ps.lostball)
    + ((ps.steal + ps.block + ps.defense + ps.defensex2) - ps."1on1lost" - ps.penaltymade - ps.norebound - ps.twominutes - ps.redcard - ps.bluecard)
  FROM public.player_stats ps
  WHERE ps.playerid = p_player_id
    AND ps.matchid = p_match_id;
$$ LANGUAGE sql STABLE;

CREATE OR REPLACE FUNCTION public.set_player_stats_value()
RETURNS trigger AS $$
BEGIN
  NEW."value" := public.compute_player_value(NEW.playerid, NEW.matchid);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS player_stats_set_value_on_write ON public.player_stats;
CREATE TRIGGER player_stats_set_value_on_write
BEFORE INSERT OR UPDATE ON public.player_stats
FOR EACH ROW
EXECUTE FUNCTION public.set_player_stats_value();
